const GA_MEASUREMENT_ID='G-70B346T2ZZ';
(function initAnalytics(){
  if(document.querySelector(`script[src*="googletagmanager.com/gtag/js?id=${GA_MEASUREMENT_ID}"]`)) return;
  const s=document.createElement('script');
  s.async=true;
  s.src='https://www.googletagmanager.com/gtag/js?id='+GA_MEASUREMENT_ID;
  document.head.appendChild(s);
  window.dataLayer=window.dataLayer||[];
  window.gtag=window.gtag||function(){dataLayer.push(arguments)};
  gtag('js',new Date());
  gtag('config',GA_MEASUREMENT_ID);
})();
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
const NAV=[['/','Início'],['/events.html','Eventos'],['/fighters.html','Lutadores'],['/stats.html','Estatísticas'],['/news.html','Notícias'],['/stats.html','Ranqueamentos'],['/loja.html','🛒 Loja'],['/pro.html','PRO']];
function initNav(){const nav=document.querySelector('.nav');if(!nav)return;const until=Number(localStorage.getItem('FZ_PRO_UNTIL')||0),pro=until>Date.now();nav.innerHTML=`<a class="brand" href="/"><span class="crown">♛</span>FIGHT<span>ZONE</span></a><button class="menu-btn" aria-label="Menu">☰</button><nav class="links">${NAV.map(([u,n])=>`<a class="${location.pathname===u?'active':''}" href="${u}">${n}</a>`).join('')}</nav><form class="top-search" action="/fighters.html"><input name="q" placeholder="Buscar luta, atleta..."><button>⌕</button></form><a class="account-btn" href="/pro.html">${pro?'👑 PRO ativo':'Minha conta'}</a>`;nav.querySelector('.menu-btn').onclick=()=>nav.querySelector('.links').classList.toggle('open');if(location.pathname==='/'&&!document.getElementById('store-home-banner')){const banner=document.createElement('section');banner.id='store-home-banner';banner.style.cssText='padding:14px 0;background:linear-gradient(90deg,#180707,#0b0d11,#180707);border-bottom:1px solid #5b2020';banner.innerHTML=`<div class="wrap" style="display:flex;align-items:center;justify-content:space-between;gap:18px;flex-wrap:wrap"><div><b style="color:#fff;font-size:1rem">🛒 NOVA LOJA FIGHT ZONE</b><div style="color:#aeb7c2;font-size:.85rem">Guias, packs e combo com PRO a partir de R$ 9,90.</div></div><a class="btn" href="/loja.html">VER LOJA →</a></div>`;document.querySelector('header.top')?.insertAdjacentElement('afterend',banner)}}
function ago(d){const ms=Date.now()-new Date(d).getTime(),h=Math.max(1,Math.round(ms/36e5));return h<24?`HÁ ${h}H`:`HÁ ${Math.max(1,Math.round(h/24))}D`}
async function loadLiveNews(target='live-news',limit=10){const el=document.getElementById(target);if(!el)return;try{const d=await(await fetch('/api/news?limit='+limit,{cache:'no-store'})).json();el.innerHTML=d.items.map((x,i)=>{const q=new URLSearchParams({t:x.title,s:x.source,d:x.pubDate,img:x.image,cat:x.category});return `<a class="news-card ${i===0?'news-main':''}" href="/noticia.html?${q}"><img src="${esc(x.image)}" alt="${esc(x.title)}"><div class="news-copy"><div><span class="news-tag">${esc(x.category)}</span><small>${ago(x.pubDate)} · ${esc(x.source)}</small></div><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p><b>Ler no Fight Zone →</b></div></a>`}).join('');const u=document.getElementById('live-updated');if(u)u.textContent='Atualizado '+new Date(d.updatedAt).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}catch(e){el.innerHTML='<div class="notice">Não foi possível atualizar agora.</div>'}}
function renderFighters(){const grid=document.getElementById('fighters-grid');if(!grid||!window.FIGHTERS)return;const params=new URLSearchParams(location.search);let current=params.get('division')||'all';const search=document.getElementById('fighter-search'),urlQ=params.get('q')||'';if(search&&urlQ)search.value=urlQ;document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b.dataset.filter===current));const draw=()=>{const q=(search?.value||'').toLowerCase(),list=FIGHTERS.filter(f=>(current==='all'||f.key===current)&&(f.name.toLowerCase().includes(q)||f.division.toLowerCase().includes(q)));grid.innerHTML=list.map(f=>`<a class="fighter-card" href="/fighter.html?slug=${f.slug}"><img loading="lazy" src="/api/fighter-image?slug=${f.slug}" alt="${esc(f.name)}"><div><span>${esc(f.division)}</span><h3>${esc(f.name)}</h3><small>${esc(f.flag)} ${esc(f.country)}</small><b>Ver estatísticas →</b></div></a>`).join('')||'<div class="notice">Nenhum lutador encontrado.</div>'};document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');current=b.dataset.filter;draw()});search?.addEventListener('input',draw);draw()}
function renderFeaturedFighters(){const el=document.getElementById('featured-fighters');if(!el||!window.FIGHTERS)return;const slugs=['ilia-topuria','charles-oliveira','alex-pereira','islam-makhachev','jon-jones','conor-mcgregor','khabib-nurmagomedov','ciryl-gane'];el.innerHTML=slugs.map(s=>FIGHTERS.find(f=>f.slug===s)).filter(Boolean).map(f=>`<a class="fighter-mini" href="/fighter.html?slug=${f.slug}"><img src="/api/fighter-image?slug=${f.slug}" alt="${esc(f.name)}"><div><h3>${esc(f.name)}</h3><span>${esc(f.division)}</span><small>${esc(f.flag)} ${esc(f.country)}</small><b>Ver estatísticas →</b></div></a>`).join('')}
async function renderFighterProfile(){const el=document.getElementById('fighter-profile');if(!el||!window.FIGHTERS)return;const slug=new URLSearchParams(location.search).get('slug'),f=FIGHTERS.find(x=>x.slug===slug);if(!f){el.innerHTML='<div class="notice">Lutador não encontrado.</div>';return}document.title=f.name+' | Fight Zone';el.innerHTML=`<div class="profile-head"><img src="/api/fighter-image?slug=${f.slug}" alt="${esc(f.name)}"><div><span class="kicker">${esc(f.division)}</span><h1>${esc(f.name)}</h1><p>${esc(f.flag)} ${esc(f.country)}</p><div id="fighter-basic" class="stat-row"><div><b>Cartel</b><span>Carregando…</span></div><div><b>Altura</b><span>—</span></div><div><b>Alcance</b><span>—</span></div><div><b>Peso</b><span>—</span></div></div></div></div><section class="fighter-stats"><h2>Estatísticas do lutador</h2><div id="fight-stats" class="stat-grid"><div class="statbox"><b>SLpM</b><span>—</span><small>Golpes significativos por minuto</small></div><div class="statbox"><b>Precisão</b><span>—</span><small>Golpes significativos</small></div><div class="statbox"><b>SApM</b><span>—</span><small>Golpes absorvidos por minuto</small></div><div class="statbox"><b>Defesa</b><span>—</span><small>Defesa de golpes</small></div><div class="statbox"><b>Quedas</b><span>—</span><small>Média por 15 min.</small></div><div class="statbox"><b>Def. quedas</b><span>—</span><small>Defesa de quedas</small></div></div><p class="muted stat-source">Dados públicos consultados no UFCStats quando disponíveis.</p></section>`;try{const d=await(await fetch('/api/fighter-stats?slug='+slug+'&name='+encodeURIComponent(f.name))).json(),s=d.stats||{},basic=document.querySelectorAll('#fighter-basic span');[d.record||'—',s.height||'—',s.reach||'—',s.weight||'—'].forEach((v,i)=>basic[i].textContent=v);const vals=[s.slpm,s.strAcc,s.sapm,s.strDef,s.tdAvg,s.tdDef];document.querySelectorAll('#fight-stats .statbox>span').forEach((x,i)=>x.textContent=vals[i]||'—')}catch(e){}}
async function fighterCompareBox(side,slug,name){try{const d=await(await fetch('/api/fighter-stats?slug='+encodeURIComponent(slug)+'&name='+encodeURIComponent(name))).json(),s=d.stats||{};return `<div class="compare-fighter"><img src="/api/fighter-image?slug=${esc(slug)}" alt="${esc(name)}"><h2>${esc(name)}</h2><div class="compare-stats"><div><b>${esc(d.record||'—')}</b><span>Cartel</span></div><div><b>${esc(s.height||'—')}</b><span>Altura</span></div><div><b>${esc(s.reach||'—')}</b><span>Alcance</span></div><div><b>${esc(s.strAcc||'—')}</b><span>Precisão</span></div><div><b>${esc(s.slpm||'—')}</b><span>SLpM</span></div><div><b>${esc(s.tdAvg||'—')}</b><span>Quedas</span></div></div><a class="btn ghost" href="/fighter.html?slug=${esc(slug)}">Perfil completo</a></div>`}catch(e){return `<div class="compare-fighter"><img src="/api/fighter-image?slug=${esc(slug)}" alt="${esc(name)}"><h2>${esc(name)}</h2><p>Estatísticas indisponíveis no momento.</p></div>`}}
async function renderFightCard(){const el=document.getElementById('fight-card-detail');if(!el)return;const p=new URLSearchParams(location.search),n1=p.get('n1')||'Lutador 1',s1=p.get('s1')||'',n2=p.get('n2')||'Lutador 2',s2=p.get('s2')||'',title=p.get('title')||`${n1} vs ${n2}`,event=p.get('event')||'UFC',division=p.get('division')||'MMA';document.title=title+' | Fight Zone';el.innerHTML=`<div class="fight-detail-head"><span class="kicker">${esc(event)} · ${esc(division)}</span><h1>${esc(title)}</h1><p class="muted">Clique nos perfis para ver ainda mais estatísticas.</p></div><div class="fight-compare-loading skeleton"></div>`;const [a,b]=await Promise.all([fighterCompareBox('left',s1,n1),fighterCompareBox('right',s2,n2)]);el.innerHTML=`<div class="fight-detail-head"><span class="kicker">${esc(event)} · ${esc(division)}</span><h1>${esc(title)}</h1><p class="muted">Comparação de estatísticas dos dois lutadores.</p></div><div class="fight-compare">${a}<div class="vs-mark">VS</div>${b}</div>`}
async function renderNewsArticle(){const el=document.getElementById('news-article');if(!el)return;const p=new URLSearchParams(location.search),title=p.get('t')||'Notícia Fight Zone',source=p.get('s')||'Notícias',date=p.get('d')||'',img=p.get('img')||'/api/news-image?title=Fight%20Zone&cat=MMA',cat=p.get('cat')||'MMA';let summary='';try{const d=await(await fetch('/api/news?limit=40',{cache:'no-store'})).json();summary=(d.items.find(x=>x.title===title&&x.source===source)||{}).summary||''}catch(e){}document.title=title+' | Fight Zone';el.innerHTML=`<img class="article-hero-img" src="${esc(img)}" alt="${esc(title)}"><span class="news-tag">${esc(cat)}</span><h1>${esc(title)}</h1><p class="news-meta">${esc(source)}${date?' · '+new Date(date).toLocaleString('pt-BR'):''}</p><p class="lead">${esc(summary||'A Fight Zone acompanha esta atualização do mundo da luta.')}</p><h2>Resumo Fight Zone</h2><p>Esta atualização foi selecionada pelo monitor de notícias do Fight Zone e apresentada em português. Novas informações aparecem na página de notícias conforme o feed é renovado.</p><div class="actions"><a class="btn" href="/news.html">Mais notícias</a><a class="btn ghost" href="/fighters.html">Lutadores</a></div>`}
async function startPro(){const b=document.getElementById('buy-pro');if(!b)return;b.onclick=async()=>{b.disabled=true;b.textContent='Abrindo checkout…';try{const d=await(await fetch('/api/create-infinitepay',{method:'POST'})).json();if(d.url)location.href=d.url;else throw 0}catch(e){b.disabled=false;b.textContent='Tentar novamente';alert('Não foi possível abrir o checkout agora.')}}}
async function confirmPro(){const el=document.getElementById('pro-confirm');if(!el)return;const p=new URLSearchParams(location.search),payload={order_nsu:p.get('order_nsu'),transaction_nsu:p.get('transaction_nsu'),slug:p.get('slug')};if(!payload.order_nsu||!payload.transaction_nsu||!payload.slug){el.innerHTML='<div class="notice">Não encontrei os dados do pagamento. Volte ao PRO e tente novamente.</div>';return}try{const d=await(await fetch('/api/infinitepay-status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})).json();if(d.verified){const until=Date.now()+30*864e5;localStorage.setItem('FZ_PRO_UNTIL',String(until));el.innerHTML=`<div class="success-box"><h1>👑 PRO ATIVADO</h1><p>Pagamento confirmado. Seu acesso neste dispositivo está ativo por 30 dias.</p>${d.receipt_url?`<a class="btn ghost" href="${d.receipt_url}" target="_blank">Ver comprovante</a>`:''}<a class="btn" href="/">Ir para o Fight Zone</a></div>`}else el.innerHTML='<div class="notice">O pagamento ainda não foi confirmado. Atualize esta página em alguns segundos.</div>'}catch(e){el.innerHTML='<div class="notice">Não foi possível confirmar o pagamento agora.</div>'}}
document.addEventListener('DOMContentLoaded',()=>{initNav();renderFighters();renderFeaturedFighters();renderFighterProfile();renderFightCard();renderNewsArticle();startPro();confirmPro();loadLiveNews('live-news',9)});