(()=>{const extra=[
['cody-garbrandt','Cody Garbrandt','Peso-galo','bantam','Estados Unidos','🇺🇸'],['mario-bautista','Mario Bautista','Peso-galo','bantam','Estados Unidos','🇺🇸'],['kyler-phillips','Kyler Phillips','Peso-galo','bantam','Estados Unidos','🇺🇸'],['adrian-yanez','Adrian Yanez','Peso-galo','bantam','Estados Unidos','🇺🇸'],['chris-gutierrez','Chris Gutierrez','Peso-galo','bantam','Estados Unidos','🇺🇸'],
['dan-ige','Dan Ige','Peso-pena','feather','Estados Unidos','🇺🇸'],['cub-swanson','Cub Swanson','Peso-pena','feather','Estados Unidos','🇺🇸'],['sodiq-yusuff','Sodiq Yusuff','Peso-pena','feather','Nigéria','🇳🇬'],['pat-sabatini','Pat Sabatini','Peso-pena','feather','Estados Unidos','🇺🇸'],
['drew-dober','Drew Dober','Peso-leve','light','Estados Unidos','🇺🇸'],['grant-dawson','Grant Dawson','Peso-leve','light','Estados Unidos','🇺🇸'],['jalin-turner','Jalin Turner','Peso-leve','light','Estados Unidos','🇺🇸'],['rafael-dos-anjos','Rafael dos Anjos','Peso-leve','light','Brasil','🇧🇷'],['alexander-hernandez','Alexander Hernandez','Peso-leve','light','Estados Unidos','🇺🇸'],['esteban-ribovics','Esteban Ribovics','Peso-leve','light','Argentina','🇦🇷'],['king-green','King Green','Peso-leve','light','Estados Unidos','🇺🇸'],
['neil-magny','Neil Magny','Meio-médio','welter','Estados Unidos','🇺🇸'],['michael-page','Michael Page','Meio-médio','welter','Inglaterra','🏴'],['khaos-williams','Khaos Williams','Meio-médio','welter','Estados Unidos','🇺🇸'],['court-mcgee','Court McGee','Meio-médio','welter','Estados Unidos','🇺🇸'],
['michel-pereira','Michel Pereira','Peso-médio','middle','Brasil','🇧🇷'],['roman-kopylov','Roman Kopylov','Peso-médio','middle','Rússia','🇷🇺'],['chris-curtis','Chris Curtis','Peso-médio','middle','Estados Unidos','🇺🇸'],['kelvin-gastelum','Kelvin Gastelum','Peso-médio','middle','Estados Unidos','🇺🇸'],['ateba-gautier','Ateba Gautier','Peso-médio','middle','Camarões','🇨🇲'],['andrey-pulyaev','Andrey Pulyaev','Peso-médio','middle','Rússia','🇷🇺'],['ismail-naurdiev','Ismail Naurdiev','Peso-médio','middle','Áustria','🇦🇹'],
['paul-craig','Paul Craig','Meio-pesado','lhw','Escócia','🏴'],['azamat-murzakanov','Azamat Murzakanov','Meio-pesado','lhw','Rússia','🇷🇺'],['bogdan-guskov','Bogdan Guskov','Meio-pesado','lhw','Uzbequistão','🇺🇿'],
['mick-parkin','Mick Parkin','Peso-pesado','heavy','Inglaterra','🏴'],['rodrigo-nascimento','Rodrigo Nascimento','Peso-pesado','heavy','Brasil','🇧🇷'],['shamil-gaziev','Shamil Gaziev','Peso-pesado','heavy','Bahrein','🇧🇭'],
['tracy-cortez','Tracy Cortez','Peso-mosca feminino','women','Estados Unidos','🇺🇸'],['jasmine-jasudavicius','Jasmine Jasudavicius','Peso-mosca feminino','women','Canadá','🇨🇦'],['mayra-bueno-silva','Mayra Bueno Silva','Peso-galo feminino','women','Brasil','🇧🇷'],['macy-chiasson','Macy Chiasson','Peso-galo feminino','women','Estados Unidos','🇺🇸'],['amanda-lemos','Amanda Lemos','Peso-palha feminino','women','Brasil','🇧🇷'],['marina-rodriguez','Marina Rodriguez','Peso-palha feminino','women','Brasil','🇧🇷'],['wang-cong','Wang Cong','Peso-mosca feminino','women','China','🇨🇳']
].map(([slug,name,division,key,country,flag])=>({slug,name,division,key,country,flag}));window.FIGHTERS=window.FIGHTERS||[];const seen=new Set(window.FIGHTERS.map(f=>f.slug));for(const f of extra)if(!seen.has(f.slug)){window.FIGHTERS.push(f);seen.add(f.slug)}})();