window.FIGHTERS=[
['joshua-van','Joshua Van','Peso-mosca','fly','Campeão'],['alexandre-pantoja','Alexandre Pantoja','Peso-mosca','fly','#1'],['manel-kape','Manel Kape','Peso-mosca','fly','#2'],['brandon-royval','Brandon Royval','Peso-mosca','fly','#3'],['tatsuro-taira','Tatsuro Taira','Peso-mosca','fly','#4'],['kyoji-horiguchi','Kyoji Horiguchi','Peso-mosca','fly','#5'],['brandon-moreno','Brandon Moreno','Peso-mosca','fly','Destaque'],['amir-albazi','Amir Albazi','Peso-mosca','fly','Destaque'],
['petr-yan','Petr Yan','Peso-galo','bantam','Campeão'],['merab-dvalishvili','Merab Dvalishvili','Peso-galo','bantam','#1'],['song-yadong','Song Yadong','Peso-galo','bantam','#2'],['sean-omalley','Sean O’Malley','Peso-galo','bantam','#3'],['mario-bautista','Mario Bautista','Peso-galo','bantam','#4'],['umar-nurmagomedov','Umar Nurmagomedov','Peso-galo','bantam','#5'],['cory-sandhagen','Cory Sandhagen','Peso-galo','bantam','#6'],['raoni-barcelos','Raoni Barcelos','Peso-galo','bantam','Brasil'],
['alexander-volkanovski','Alexander Volkanovski','Peso-pena','feather','Destaque'],['diego-lopes','Diego Lopes','Peso-pena','feather','Brasil'],['movsar-evloev','Movsar Evloev','Peso-pena','feather','Destaque'],['yair-rodriguez','Yair Rodriguez','Peso-pena','feather','Destaque'],['brian-ortega','Brian Ortega','Peso-pena','feather','Destaque'],['arnold-allen','Arnold Allen','Peso-pena','feather','Destaque'],
['justin-gaethje','Justin Gaethje','Peso-leve','light','Campeão'],['ilia-topuria','Ilia Topuria','Peso-leve','light','#1'],['arman-tsarukyan','Arman Tsarukyan','Peso-leve','light','#2'],['charles-oliveira','Charles Oliveira','Peso-leve','light','#3'],['max-holloway','Max Holloway','Peso-leve','light','#4'],['paddy-pimblett','Paddy Pimblett','Peso-leve','light','#5'],['benoit-saint-denis','Benoît Saint Denis','Peso-leve','light','Destaque'],['mauricio-ruffy','Mauricio Ruffy','Peso-leve','light','Brasil'],
['islam-makhachev','Islam Makhachev','Meio-médio','welter','Campeão'],['ian-machado-garry','Ian Machado Garry','Meio-médio','welter','#1'],['carlos-prates','Carlos Prates','Meio-médio','welter','#2'],['michael-morales','Michael Morales','Meio-médio','welter','#3'],['jack-della-maddalena','Jack Della Maddalena','Meio-médio','welter','#4'],['gabriel-bonfim','Gabriel Bonfim','Meio-médio','welter','Brasil'],['belal-muhammad','Belal Muhammad','Meio-médio','welter','Destaque'],['kamaru-usman','Kamaru Usman','Meio-médio','welter','Destaque'],
['sean-strickland','Sean Strickland','Peso-médio','middle','Campeão'],['khamzat-chimaev','Khamzat Chimaev','Peso-médio','middle','#1'],['dricus-du-plessis','Dricus Du Plessis','Peso-médio','middle','#2'],['nassourdine-imavov','Nassourdine Imavov','Peso-médio','middle','#3'],['caio-borralho','Caio Borralho','Peso-médio','middle','Brasil'],['israel-adesanya','Israel Adesanya','Peso-médio','middle','Destaque'],['robert-whittaker','Robert Whittaker','Peso-médio','middle','Destaque'],
['carlos-ulberg','Carlos Ulberg','Meio-pesado','lhw','Campeão'],['magomed-ankalaev','Magomed Ankalaev','Meio-pesado','lhw','#1'],['jiri-prochazka','Jiří Procházka','Meio-pesado','lhw','#2'],['alex-pereira','Alex Pereira','Meio-pesado','lhw','#3'],['khalil-rountree-jr','Khalil Rountree Jr.','Meio-pesado','lhw','Destaque'],['paulo-costa','Paulo Costa','Meio-pesado','lhw','Brasil'],['jamahal-hill','Jamahal Hill','Meio-pesado','lhw','Destaque'],
['ciryl-gane','Ciryl Gane','Peso-pesado','heavy','Campeão'],['tom-aspinall','Tom Aspinall','Peso-pesado','heavy','#1'],['alexander-volkov','Alexander Volkov','Peso-pesado','heavy','#2'],['sergei-pavlovich','Sergei Pavlovich','Peso-pesado','heavy','#3'],['curtis-blaydes','Curtis Blaydes','Peso-pesado','heavy','Destaque'],['waldo-cortes-acosta','Waldo Cortes Acosta','Peso-pesado','heavy','Destaque'],['vitor-petrino','Vitor Petrino','Peso-pesado','heavy','Brasil'],['jailton-almeida','Jailton Almeida','Peso-pesado','heavy','Brasil'],
['mackenzie-dern','Mackenzie Dern','Peso-palha feminino','women','Campeã'],['zhang-weili','Zhang Weili','Peso-palha feminino','women','#1'],['virna-jandiroba','Virna Jandiroba','Peso-palha feminino','women','Brasil'],['tatiana-suarez','Tatiana Suarez','Peso-palha feminino','women','Destaque'],['denise-gomes','Denise Gomes','Peso-palha feminino','women','Brasil'],['valentina-shevchenko','Valentina Shevchenko','Peso-mosca feminino','women','Destaque'],['manon-fiorot','Manon Fiorot','Peso-mosca feminino','women','Destaque'],['erin-blanchfield','Erin Blanchfield','Peso-mosca feminino','women','Destaque'],['kayla-harrison','Kayla Harrison','Peso-galo feminino','women','Destaque'],['julianna-pena','Julianna Peña','Peso-galo feminino','women','Destaque']
].map(([slug,name,division,key,status])=>({slug,name,division,key,status}));