function loadEntitlements(){try{return JSON.parse(localStorage.getItem('FZ_STORE_ENTITLEMENTS')||'{}')}catch(e){return {}}}
function renderProduct(){
  const root=document.getElementById('product-root');if(!root)return;
  const item=new URLSearchParams(location.search).get('item');
  const ent=loadEntitlements();
  if(item==='guia'&&!ent.guia){root.innerHTML='<div class="locked"><h1>Conteúdo bloqueado</h1><p>Este guia é liberado automaticamente após a confirmação do pagamento.</p><a class="btn" href="/loja.html">Ir para a loja</a></div>';return}
  if(item==='pack'&&!ent.pack){root.innerHTML='<div class="locked"><h1>Conteúdo bloqueado</h1><p>O Pack Fight Night é liberado automaticamente após a confirmação do pagamento.</p><a class="btn" href="/loja.html">Ir para a loja</a></div>';return}
  if(item==='pack')renderPack(root);else renderGuide(root);
}
function guideSections(){return `<span class="kicker">GUIA FIGHT ZONE</span><h1>MMA sem enrolação</h1><p class="lead">O básico que você precisa saber para assistir a uma luta e entender o que está acontecendo.</p><div class="lesson"><h2>1. Como uma luta é dividida</h2><p>A maioria das lutas profissionais de MMA tem 3 rounds. Disputas principais e lutas de cinturão costumam ter 5 rounds. Cada round normalmente dura 5 minutos.</p></div><div class="lesson"><h2>2. Como uma luta termina</h2><p><b>KO:</b> o atleta não consegue continuar após um golpe. <b>TKO:</b> árbitro ou médico interrompe. <b>Finalização:</b> desistência por chave ou estrangulamento. <b>Decisão:</b> os juízes escolhem o vencedor após todos os rounds.</p></div><div class="lesson"><h2>3. O que os juízes observam</h2><p>O critério principal é dano e efetividade. Golpes significativos, ataques de finalização, quedas e controle que gerem ofensiva real pesam mais do que simplesmente ficar em uma posição sem produzir.</p></div><div class="lesson"><h2>4. Categorias de peso</h2><p>As divisões existem para aproximar atletas de tamanho e peso semelhantes. Entre as mais conhecidas estão peso-mosca, galo, pena, leve, meio-médio, médio, meio-pesado e pesado.</p></div><div class="lesson"><h2>5. Glossário rápido</h2><p><b>Striking:</b> trocação em pé. <b>Grappling:</b> luta agarrada. <b>Takedown:</b> queda. <b>Clinch:</b> disputa agarrada em pé. <b>Ground and pound:</b> golpes no chão. <b>Submission:</b> tentativa de finalização.</p></div><div class="lesson"><h2>6. Checklist antes do evento</h2><ul class="checklist"><li>☐ Veja quem faz a luta principal e o coevento</li><li>☐ Confira a categoria de peso</li><li>☐ Compare cartel e estilo dos atletas</li><li>☐ Observe alcance, altura e ritmo de luta</li><li>☐ Durante a luta, anote quem causou mais dano em cada round</li></ul></div>`}
function renderGuide(root){document.title='Guia MMA sem enrolação | Fight Zone';root.innerHTML=`<article class="product-content">${guideSections()}<div class="lesson"><h2>Use junto com o Fight Zone</h2><p>Abra os perfis de lutadores e os cards do site para comparar estatísticas enquanto acompanha o evento.</p><a class="btn" href="/fighters.html">Ver lutadores</a></div></article>`}
function renderPack(root){document.title='Pack Fight Night | Fight Zone';root.innerHTML=`<article class="product-content">${guideSections()}<span class="kicker">EXTRA DO PACK</span><h2>Scorecard Fight Night</h2><p class="muted">Use este quadro para acompanhar uma luta round a round.</p><div class="scorecard"><div class="scorebox"><h3>Round 1</h3><p>Dano: ________</p><p>Quedas: ________</p><p>Controle efetivo: ________</p><p>Vencedor: ________</p></div><div class="scorebox"><h3>Round 2</h3><p>Dano: ________</p><p>Quedas: ________</p><p>Controle efetivo: ________</p><p>Vencedor: ________</p></div><div class="scorebox"><h3>Round 3</h3><p>Dano: ________</p><p>Quedas: ________</p><p>Controle efetivo: ________</p><p>Vencedor: ________</p></div><div class="scorebox"><h3>Rounds 4 e 5</h3><p>Use em lutas de 5 rounds.</p><p>R4: ________</p><p>R5: ________</p><p>Resultado final: ________</p></div></div><div class="lesson"><h2>Modelo de palpites e resultados</h2><p>Luta: __________________________</p><p>Seu palpite: ____________________</p><p>Método esperado: _______________</p><p>Resultado real: _________________</p><p>O que decidiu a luta: ___________</p></div><div class="lesson"><h2>Checklist de card completo</h2><ul class="checklist"><li>☐ Escolha 3 lutas para acompanhar com mais atenção</li><li>☐ Compare estatísticas no Fight Zone</li><li>☐ Anote seu palpite antes da luta</li><li>☐ Pontue cada round sem olhar comentários externos</li><li>☐ Compare sua leitura com o resultado oficial</li></ul></div></article>`}
document.addEventListener('DOMContentLoaded',renderProduct);